### ISSUE TITLE
How to add additional tf version to tfswitch

### ISSUE THREAD

**Issue by BernhardLenz** [warrensbox/terraform-switcher#101]
On my MacOs I have tf 13 installed (using brew) and then installed tfswitch (using brew). 
Now i'd like to install tf 12 and have it switched with tfswitch but can't find any documentation on how to add tf12 to tfswitch.

The output of the tfswitch command is
```
$tfswitch
Reading required version from terraform file, constraint: >= 0.12
Matched version: 0.13.2
Switched terraform to version "0.13.2" 

$tfswitch -v      
Version: 0.8.832

```

**Comment by warrensbox** [comment]
@BernhardLenz in your directory, in your terraform file, you probably have this line:
```sh
terraform {
  required_version = ">= 0.12.9"

}
```

With `tfswitch`, it automatically gets any version that is *higher than or equals* (>=) to `0.12.9`. In your case, it got the latest version which is `0.13.2`
I suggest you refactor that line to the version`~> 0.12.0`(pessimistic lock) . This will only get you the latest 0.12 version. Your terraform file should look something like this:
```
terraform {
  required_version = "~> 0.12.0"

}
```
Otherwise, you can manually provide the version like this:
`tfswitch 0.12.9`
With whatever version you desire. 
<img src="https://s3.us-east-2.amazonaws.com/kepler-images/warrensbox/tfswitch/tfswitch-v4.gif#1" alt="drawing" style="width: 370px;"/>
