### ISSUE TITLE
Natural sorting is required for newer versions to be listed as "recent"

### ISSUE THREAD

**Issue by skyzyx** [warrensbox/terraform-switcher#157]
As of today, `0.14.9` is marked as _recent_, while 0.14.10 is not. I'm guessing this is because the version numbers are sorted using standard `sort` instead of a natural sorting algorithm.

**Comment by warrensbox** [comment]
@skyzyx 
Hey Ryan, what command are you running:
When I run ` tfswitch --latest-stable 0.14`, I see: 
<img width="461" alt="Screen Shot 2021-04-14 at 9 16 53 AM" src="https://user-images.githubusercontent.com/38867521/114728745-fd4c5400-9d04-11eb-84bb-0b9cb04d7a94.png">

When I run `tfswitch --latest`, I see:
<img width="949" alt="Screen Shot 2021-04-14 at 9 16 15 AM" src="https://user-images.githubusercontent.com/38867521/114728910-22d95d80-9d05-11eb-99d0-477539333ea3.png">

When I run `tfswitch`, I see 14.10 at the top:
<img width="310" alt="Screen Shot 2021-04-14 at 9 14 20 AM" src="https://user-images.githubusercontent.com/38867521/114729027-3a184b00-9d05-11eb-8017-027d55ca5f16.png">

Can you post a screenshot of what you're seeing?

**Comment by skyzyx** [comment]
When I posted this, I was seeing `0.14.9` marked as _*recent_, but 0.14.10 was not marked this way, and was lower in the list.

Perhaps I don't understand the recency algorithm?

This is what I see this morning, after 0.15.0 has been released.

<img width="387" alt="Screen Shot 2021-04-14 at 9 43 14 AM" src="https://user-images.githubusercontent.com/39447/114747810-186b9380-9d06-11eb-9b39-db92d8eb351a.png">

**Comment by warrensbox** [comment]
@skyzyx the `*recent` here means that that's the most recent version that you have used on your machine. In this case, it means - you have "recently" used version 0.14.10 (this does not mean this is the latest version released by Hashicorp).
`tfswitch` remember the last 3 recent version that you have used. That way, it's easy to switch instead of scrolling all the way down.

For example : (the order of switching to different terraform version using tfswitch)
Project 1 :` terraform 0.14.8` -> Project 2 :` terraform 0.14.9`   -> Project 3 : `terraform 0.11.13`  -> Project 4 :` terraform 0.10.08 `

The dropdown should show: 
0.10.08  *recent
0.11.13  *recent
0.14.9  *recent
Since these are the 3 last recent version that was used.
