### ISSUE TITLE
Killed: 9 Terraform on Mac Big Sur

### ISSUE THREAD

**Issue by sarasensible** [warrensbox/terraform-switcher#307]
Using tfswitch on Big Sur when I try to run terraform I get "killed: 9".  `brew install terraform` works.

My installation path is to /usr/local/bin/terraform, I tried switching to one in my Users path but it didn't help.

Any guidance would be greatly appreciated.

**Comment by yermulnik** [comment]
This doesn't seem to be a `tfswitch` issue since `tfswitch` in it essence is only a helper tool to simplify `terraform` binaries download.
What you described looks to be related to https://github.com/warrensbox/terraform-switcher/issues/306 and you may find workarounds in e.g. this thread https://github.com/hashicorp/terraform/issues/23033 in Terraform repo.

Please feel free to re-open if you think `tfswitch` has something to do about it.
