### ISSUE TITLE
"terraform_x.y.z" will damage your computer. You should move it to the Bin

### ISSUE THREAD

**Issue by jochenhebbrecht** [warrensbox/terraform-switcher#310]
Hi,

I've just installed `tfswitch`on _OS X Ventura 13.3.1 (a)_ using `brew install`. After that, I installed a specific version and tried to get the version of it - to verify if installation was OK. But I got the following error:
```bash
❯ tfswitch -b ~/.bin/terraform 1.1.5
Switched terraform to version "1.1.5"
❯ terraform -version
[1]    77738 killed     terraform -version
```

At that moment, I also get the following pop-up on the screen:
<img width="453" alt="Screenshot 2023-05-23 at 21 40 25" src="https://github.com/warrensbox/terraform-switcher/assets/2405227/ff403de8-4fe6-4bd8-9b59-2edd59b57516">

Any idea what could be causing this?
Jochen

**Comment by yermulnik** [comment]
Related:
* https://github.com/warrensbox/terraform-switcher/issues/306
* https://github.com/warrensbox/terraform-switcher/issues/307

If you have any idea what `terraform-switcher` can do about this, please re-open this issue.

**Comment by daniel-zr** [comment]
> If you have any idea what `terraform-switcher` can do about this, please re-open this issue.

This is the root cause https://support.hashicorp.com/hc/en-us/articles/13177506317203

We need to re-download the terraform binary. I was getting this issue when trying to use an old version for a legacy project. I was trying to use the latest 0.13 but since I had that downloaded at some point, tfswitch wasn't getting a new binary. I picked a different 0.13 version and tfswitch downloaded it and it worked perfectly. 

Fix: either delete your existing terraform binary for the version you're trying to use or use a different version.

**Comment by fabien-chebel** [comment]
I came across this issue today while attempting to run an older version of terraform.

I was able to force tfswitch to re-download a correctly signed version of the `terraform` binary by removing the current one from the cache directory located in `~/.terraform.versions/`.

**Comment by MatthewLymer** [comment]
Thank you @fabien-chebel, this solved the problem for me (M1 macbook).
