### ISSUE TITLE
OpenTofu Support

### ISSUE THREAD

**Issue by cameronattard** [warrensbox/terraform-switcher#315]
**Is your feature request related to a problem? Please describe.**
Per https://opentf.org/announcement, a new fork of Terraform, OpenTF is being created.

**Describe the solution you'd like**
Allow using `tfswitch` to install and manage OpenTF versions in addition to Terraform versions.

**Comment by nitrocode** [comment]
Wouldn't something like the `--mirror` flag work for opentf ?

https://github.com/warrensbox/terraform-switcher#use-custom-mirror

**Comment by roni-frantchi** [comment]
> Wouldn't something like the --mirror flag work for opentf ?

Hey @nitrocode - not quite.  
Although we are looking to be fully compatible with legacy Terraform, the binary name, command (`terraform` vs `opentf`) are all going to be different.

**Comment by nitrocode** [comment]
Same issue that affects listing versions in mirrors will also affect opentofu since there isn't a single non-paginated url containing every opentofu release.

Related issue
- https://github.com/warrensbox/terraform-switcher/issues/311

**Comment by nitrocode** [comment]
An option might be to switch from downloading terraform releases from the hashicorp page and download instead directly from github. Then it would be fairly simple to download the files from opentofu instead. The version check would then have to hit the github rest api or have an index url file passed in as an argument.

https://github.com/opentofu/opentofu/releases
https://github.com/hashicorp/terraform/releases

**Comment by nitrocode** [comment]
I made a page here that seems to line up similar to the terraform release page

https://nitrocode.github.io/opentofu/

**Comment by nitrocode** [comment]
We'll probably need a way of overriding the `versionPrefix` since opentofu's prefix is `tofu_`

It might also be nice to override the rest of these too.

https://github.com/warrensbox/terraform-switcher/blob/d7dfd1b44605b095937e94b981d24305b858ff8c/main.go#L40-L49

**Comment by MatthewJohn** [comment]
I'm interested in this issue, as we use tfswitch (or terraform-switcher ;) ) in Terrareg.

Once concern I could imagine is that, you're using Hashicorp's HCL library for obtaining the constraint from a `terraform {}` block: https://github.com/warrensbox/terraform-switcher/blob/d7dfd1b44605b095937e94b981d24305b858ff8c/main.go#L433

Do we know if OpenTofu are sticking with this format (are they planning on changing the name at some point?) and I assume they have their own fork of the libraries: https://github.com/warrensbox/terraform-switcher/blob/d7dfd1b44605b095937e94b981d24305b858ff8c/main.go#L30

**Comment by kvendingoldo** [comment]
@cameronattard @nitrocode @MatthewJohn at this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

**Comment by yermulnik** [comment]
@kvendingoldo While I have nothing against `tenv` (I tried it myself and, well, I prefer `tfswitch`, that I can run w/o any args to get just what I need — to switch to latest TF version allowed by the version constraint), I would like to ask to refrain from posting misleading info like «_A lot of users switched to that tool to unify version management in the world of Terraform_».

`tenv`: 
![image](https://github.com/warrensbox/terraform-switcher/assets/1274789/7627d1c2-8f48-41e1-b58e-3fff7a49e38c)
`tfswitch`: 
![image](https://github.com/warrensbox/terraform-switcher/assets/1274789/48125c60-5fcd-40a4-8cad-3953479dbe95)

Please be respectful and mindful.

PS: To the extent possible we'll make our best to look into OpenTofu and Terragrunt support to be implemented in `tfswitch` (though it is not a high-priority task at the moment I think). PRs are welcome since `tfswitch` has gain some energy lately.

**Comment by nitrocode** [comment]
The tenv doesn't help me unfortunately because it's not the cli that I'd need here.

Atlantis (and other apps) uses the underlying `terraform-switcher`'s go libs so those would need to be updated so we can keep the implementation of how atlantis autoupdates terraform the same as how it could autoupdate opentofu.

**Comment by yermulnik** [comment]
> Atlantis (and other apps) uses the underlying `terraform-switcher`'s go libs so those would need to be updated so we can keep the implementation of how atlantis autoupdates terraform the same as how it could autoupdate opentofu.

Thanks for the update and details.
Is what you're referring to related to https://github.com/warrensbox/terraform-switcher/issues/192 by any chance? I mean how the Atlantis (and other apps) utilizes `tfswitch` as a library?

While we're a bit short on human power to implement OpenTofu support, we welcome contributions and we'll try our best to review them as fast as our capacity allows.

**Comment by nitrocode** [comment]
It's unrelated to the issue you mentioned.

See this issue for the lower level details https://github.com/runatlantis/atlantis/issues/4339.

**Comment by MatthewJohn** [comment]
On the topic of the atlantis use of tfswitch as a library, I see they're using the, now private, GetTFList method and having to pre-query the URL beforehand due to the early-exits (or Fatals) that are used in tfswitch (https://github.com/runatlantis/atlantis/blob/513b57aa45bbae6e1217fb389adb0de4831279d0/server/core/terraform/terraform_client.go#L304C16-L304C43)).
This is maybe something of a discussion point

It seems that OpenTofu now has a static site containing release information, if we didn't want to start using the Github API: https://get.opentofu.org/tofu/.
This resembles Hashicorp's release page a bit (so much so that testing tfswitch using it, it *does* pick up a version correctly, but only shows one, I suspect because the HTML is all on one line, perhaps (need to dig into further).
Though, on another note, hashicorp *do* have a JSON version of this file (which should definitely be worth considering!).
Perhaps we could suggest to OpenTofu to implement a JSON-version of their static get.opentofu release list page.

I'd be happy to take a look - but my main concern would be how to add the logic and retaining compatibility with external library usage:
 * From what I can tell getTFList does *sort of* work for their static page (though might need a tiny bit of tweaking, but hoping it could be made compatible with both TF and tofu release pages).
 * In terms of library support, _should_ `install` and `getTfList` be public methods to allow external use? If not, can the signatures of these methods be happily changed?

I'm wondering if installDir (https://github.com/warrensbox/terraform-switcher/blob/master/lib/defaults.go#L31) could be used to toggle the directory for Terraform vs OpenTofu (and thus installed versions and GPG key could be kept independent).

Then perhaps a flag for `--distribution` for `terraform` or `opentofu` could be added? (I know there's plenty of other things that will come out of the woods when starting to implement, though!)

**Comment by nitrocode** [comment]
Thanks for implementing this @MatthewJohn 

@warrensbox will there be a release soon?

**Comment by MatthewJohn** [comment]
> Thanks for implementing this @MatthewJohn
> 
> @warrensbox will there be a release soon?

We're just doing some testing at the moment on the alpha release of this :)

**Comment by warrensbox** [comment]
Opentofu feature was released on https://github.com/warrensbox/terraform-switcher/releases/tag/v1.2.0

Latest bug fixed: v1.2.2 (mostly related to windows)
