### ISSUE TITLE
tfswitch -v should not apply anything - it should only print the tfswitch version

### ISSUE THREAD

**Issue by warrensbox** [warrensbox/terraform-switcher#443]
**Is your feature request related to a problem? Please describe.**
Currently the tfswitch -v reads config files and applies them when you pass `-v`. Previously, it only printed the tfswitch version

**Describe the solution you'd like**
tfswitch -v should not apply anything - it should only print the tfswitch version

Current:
```
warrenv@mass ~/WarrensBox/go/src/github.com/warrensbox/tfswitch/test-data/integration-tests/test_versiontf --> tfswitch -v
13:39:12.681 INFO Reading version from Terraform module at "."
13:39:12.754 INFO Reading required version from constraint: "1.6.3"
13:39:12.755 INFO Matched version: "1.6.3"
Version: v1.1.1
```

Needs to look like:
```
Version: v1.1.1
```

**Comment by MatthewJohn** [comment]
I guess there's a couple of options here:
 * Change all of the logging in parameter parsing to use debug (if it's working as normal - do people care where it detected the version from)
 * Hack a particular log level for this particular command (though, this is even harder because we don't match the command until after we've done all of the parameter parsing)
 * Switch logging to STDERR (think this has been discussed before and is standard for tools where users expect to consume output from stdout)

**Comment by yermulnik** [comment]
@MatthewJohn For this particular issue, I think it not about logging, but about `-v, --version      Displays the version of tfswitch` not needing to go through all the logic and read TF version, but bail out quickly and print version.

**Comment by yermulnik** [comment]
Like not proceed all the way down to the end of function from https://github.com/warrensbox/terraform-switcher/blob/master/lib/param_parsing/parameters.go#L54, but instead print version and exit (https://github.com/warrensbox/terraform-switcher/blob/master/main.go#L35-L41)
