### ISSUE TITLE
Difference from tfenv?

### ISSUE THREAD

**Issue by scottsb** [warrensbox/terraform-switcher#50]
This tool seems almost identical in purpose & functionality to this:
https://github.com/tfutils/tfenv

Are there any distinctive advantages this provides? A comparison section in the README describing this would be helpful.

**Comment by solsglasses** [comment]
I came with the exact same question

**Comment by nhoughto** [comment]
We didn't get to the bottom of this, but we just switched from tfenv to tfswitch because we saw strange high cpu behaviour using tfenv. It appears to wrap the terraform process at runtime, not just switch a symlink to the straight tf binary, and that wrapping process was pinning a CPU at 100%. 🤷‍♂

**Comment by warrensbox** [comment]
`tfswitch` was initially created to resolve issues that were not possible with tfenv. It was an internal tool at my company which later I open-sourced it.  I picked `golang` as the language of choice since it's easy to understand/code/contribute compared to bash. It was also easier to cross-compile for different OS and ARCH. When I first started using tfenv, a couple of years ago, it didn't provide many options that you see today. It was much more difficult to contribute a `feature`  to the standalone brew project compared to a `brew tap` project. Taps let you iterate and deploy faster.

The initial goal for `tfswitch` was to provide a simple drop-down interface for developers to pick whatever terraform version they needed. Over time, more features were contributed. Like all software, both projects has it's pros and cons. I leave it up to users to decide which one best fits their needs.
